SELECT T1.VLTOTAL SOMA_MOV_SAIDA, T2.VLCONT SOMA_PDV_FISCAL, (T1.VLTOTAL - T2.VLCONT) DIVERGENCIA

FROM (SELECT SUM(MS.VLTOTAL) VLTOTAL
						FROM 		MOV_SAIDA MS
						WHERE	1=1
						AND			MS.CODFIL = &CODFIL
						AND 		MS.NUMCXA= &NUMCXA
						AND 		MS.DTNOTA = TO_DATE(&DATA)) T1, 

					(SELECT VLCONT FROM PDV_FISCAL WHERE
					 CODFIL = &CODFIL
					 AND PDV = &NUMCXA
					 AND DATA = TO_DATE(&DATA)
					 AND TIPO = 'F') T2
						
						
						



