SELECT MS.NUMNOTA, MS.NUMCXA, MS.VLTOTAL, MS.DTNOTA, MS.STATUS, MS.CONDPGTO, MS.NUMPEDVEN, MS.CODOPER, MS.CODCLI, MS.CODVENDR, MS.CODOPER, MS.DTATUEST, MS.IDENTPROC, MS.NUMMOV, MS.NUMCOO, MS.VERSAONFE, MS.CHAVENFE, MS.NUMNFE, MS.DIGNFE, MS.STATUSNFE, MS.*
FROM MOV_SAIDA MS

WHERE 1=1
AND 		MS.CODFIL =  &CODFIL
AND   MS.NUMCXA = 24
AND 		MS.DTNOTA =  TO_DATE(&data)
--AND STATUS = 2
ORDER BY MS.CODOPER




AND 		SERIE = &SERIE
AND 		NUMNOTA = &NUMNOTA
AND NUMPEDVEN = &NUMPED
					
AND 		STATUS =  2