SELECT * FROM (SELECT DISTINCT CODFIL CODFIL, NUMCXA CXADES FROM MOV_SAIDA
WHERE 1=1
AND DTNOTA = trunc(sysdate-1)
AND TPNOTA = 512
AND IDENTPROC LIKE '%SP5.52%'
GROUP BY CODFIL, NUMCXA, IDENTPROC);

SELECT * FROM (
SELECT DISTINCT CODFIL, NUMCXA FROM MOV_SAIDA 
WHERE 1=1
AND DTNOTA = trunc(sysdate-1)
AND TPNOTA = 512
AND IDENTPROC NOT LIKE '%SP5.52%'
GROUP BY CODFIL, NUMCXA, IDENTPROC)

