SELECT CODFIL, CASE
  WHEN  CODFIL = 1 Then 'INTERLAGOS' 
  WHEN  CODFIL = 2 Then 'RIB PRETO'
  WHEN  CODFIL = 3 Then 'CAMPINAS'
  WHEN  CODFIL = 4 Then 'CONTAGEM'
  WHEN  CODFIL = 5 Then 'RAP TAVAR'
  WHEN  CODFIL = 7 Then 'RIO NORTE'
  WHEN  CODFIL = 8 Then 'TIETE'
  WHEN  CODFIL = 9 Then 'CURITIBA'
  WHEN  CODFIL = 10 Then 'SAO CAETANO'
  WHEN  CODFIL = 11 Then 'RIO BARRA'
  WHEN  CODFIL = 12 Then 'MORUMBI'
  WHEN  CODFIL = 13 Then 'BRASILIA'
  WHEN  CODFIL = 14 Then 'CD SBC'
  WHEN  CODFIL = 15 Then 'SJ CAMPOS'
  WHEN  CODFIL = 16 Then 'Ricardo Jafet'
  WHEN  CODFIL = 17 Then 'BANGU'
  WHEN  CODFIL = 19 Then 'POA'
  WHEN  CODFIL = 20 Then 'BH SUL'
  WHEN  CODFIL = 21 Then 'NITEROI'
  WHEN  CODFIL = 22 Then 'ANHANGUERA'      
  WHEN  CODFIL = 23 Then 'TAGUATINGA'      
  WHEN  CODFIL = 24 Then 'CENTERNORTE'      
  WHEN  CODFIL = 26 Then 'JACAREPAGUA'      
  WHEN  CODFIL = 27 Then 'SOROCABA'      
  WHEN  CODFIL = 28 Then 'Brasilia N.'      
  WHEN  CODFIL = 29 Then 'Uberlandia'      
  WHEN  CODFIL = 31 Then 'PLAT RJ'      
  WHEN  CODFIL = 32 Then 'Sao Leopoldo'      
  WHEN  CODFIL = 33 Then 'LONDRINA'      
  WHEN  CODFIL = 34 Then 'SJ R. PRETO'      
  WHEN  CODFIL = 35 Then 'CURITIBATUBA'      
  WHEN  CODFIL = 36 Then 'BH NORTE'      
  WHEN  CODFIL = 37 Then 'CD CAJAMAR'      
  WHEN  CODFIL = 39 Then 'SJ FLORIPA'      
  WHEN  CODFIL = 42 Then 'JAGUARE'      
  WHEN  CODFIL = 44 Then 'CAMPO GRANDE'      
  WHEN  CODFIL = 45 Then 'SAO BERNARDO'        
  WHEN  CODFIL = 46 Then 'TAMBORE'        
  WHEN  CODFIL = 48 Then 'CD ITAJAI'        
  WHEN  CODFIL = 49 Then 'NATAL'        
  WHEN  CODFIL = 50 Then 'MACEIO'        
  ELSE 'OUTROS'
  END 
  , NUMCXA
FROM MOV_SAIDA
