SELECT A.CODFIL, A.NUMCXA, A.VLTOTAL VLSAIDA, A.NUMNOTA, B.NUMNOTA, B.SERIE, SUM(B.VLTOTAL) VLITENS --*/ --  , SUBSTR(B.SERIE, 2,2)
FROM   MOV_SAIDA A
LEFT  JOIN MOV_ITSAIDA B ON A.CODFIL = B.CODFIL
                             AND A.SERIE = B.SERIE
                             AND A.NUMNOTA = B.NUMNOTA
                             AND A.DTNOTA = B.DTNOTA
WHERE  A.CODFIL = &CODFIL
       AND A.DTNOTA = TO_DATE(&DATA)
       AND A.TPNOTA = 512
       AND STATUS = 2

GROUP  BY A.CODFIL, A.NUMCXA,A.VLTOTAL, A.NUMNOTA, B.NUMNOTA, B.SERIE
--HAVING NVL(A.VLTOTAL, 0) - SUM(B.VLTOTAL) >= 0.15 OR NVL(A.VLTOTAL, 0) - SUM(B.VLTOTAL) <= -0.15
