 --Select Divergências s/ NFCE -- /MES DE NOVEMBRO
 SELECT A.CODFIL, A.NUMCXA, B.ENDERECOIP, A.DTNOTA AS DTNOTA, SUM(A.VLTOTAL) AS MOVSAIDA, B.VLCONT AS PDVFISCAL, NVL(B.VLCONT, 0) - SUM(NVL(A.VLTOTAL, 0)) AS DIVERGÊNCIA
 FROM   MOV_SAIDA A, PDV_FISCAL B, CXA_CAIXAS C
 WHERE  A.CODFIL = B.CODFIL(+)
     AND A.NUMCXA = B.PDV(+)
     AND A.DTNOTA = B.DATA(+)
     AND A.CODFIL = C.CODFIL
     AND A.NUMCXA = C.NUMCXA
     AND B.TIPO(+) = 'F'
     AND A.TPNOTA = 512
     AND A.STATUS <> 9
     AND A.CODFIL NOT IN (6, 11, 7, 14, 514, 21, 521, 26, 526 , 45, 545 , 48, 19, 519, 44)
     AND A.SERIE NOT IN ('1', '2', '3', '4', '5')
     AND A.DTNOTA BETWEEN TO_DATE('01' || TO_CHAR(SYSDATE, 'mm/yyyy'), 'dd/mm/yyyy') AND SYSDATE - 1
     AND C.MODELONF IS NULL        
 GROUP  BY A.CODFIL, A.DTNOTA, A.NUMCXA, B.ENDERECOIP, B.VLCONT
 HAVING ABS(SUM(A.VLTOTAL) - NVL(B.VLCONT, 0)) > 1



/*



















UNION

SELECT B.CODFIL, B.PDV NUMCXA, B.ENDERECOIP, B.DATA DTNOTA, B.VLCONT PDVFISCAL, B.VLCONT DIVERGENCIA
FROM   PDV_FISCAL B
WHERE  B.DATA BETWEEN '01/09/2015' AND SYSDATE - 1
       AND B.TIPO = 'F'
       AND B.VLCONT > 0
       AND NOT EXISTS (SELECT 'x'
        FROM   MOV_SAIDA A
        WHERE  A.CODFIL = B.CODFIL
	     AND A.NUMCXA = B.PDV
	     AND A.DTNOTA = B.DATA
	     AND A.TPNOTA = 512
	     AND A.STATUS <> 9
	     AND A.CODFIL NOT IN (6, 14, 519)
	     AND A.DTNOTA BETWEEN B.DATA AND B.DATA)--group by B.CODFIL, B.PDV numcxa, B.ENDERECOIP, B.DATA dtnota, b.Vlcont PDVFISCAL, b.Vlcont DIVERGENCIA
*/
