/*
Softtek Yuri
Divergência mov saida e redução z

*/
--DIVERGENCIA DE VALOR IMPRESSORA X MOV_SAIDA POR CAIXA

SELECT T1.VLTOTAL SOMA_MOV_SAIDA,
T2.VLCONT SOMA_PDV_FISCAL,
(T1.VLTOTAL - T2.VLCONT) DIVERGENCIA

FROM   (SELECT SUM(MS.VLTOTAL) VLTOTAL
FROM   MOV_SAIDA MS
WHERE  1 = 1
AND MS.CODFIL = &CODFIL
AND MS.NUMCXA = &NUMCXA
AND MS.STATUS <> 9
AND MS.TPNOTA = 512
AND MS.DTNOTA = TO_DATE(&DATA)) T1,

(SELECT VLCONT
FROM   PDV_FISCAL
WHERE  CODFIL = &CODFIL
AND PDV = &NUMCXA
AND DATA = TO_DATE(&DATA)
AND TIPO = 'F') T2
	  
	  
	  --DIVERGENCIA DE VALOR IMPRESSORA X MOV_SAIDA  POR FILIAL
	  
SELECT T1.VLSAIDA VLSAIDA,
T2.VLIMPRESSORA VLIMPRESSORA,
(VLSAIDA - VLIMPRESSORA) DIVERGENCIA
FROM   (SELECT SUM(MS.VLTOTAL) VLSAIDA
FROM   MOV_SAIDA MS
WHERE  1 = 1
AND MS.CODFIL = &CODFIL
AND MS.DTNOTA = TO_DATE(&DATA) /*exemplo de inserção: '08102015'*/
AND MS.STATUS <> 9
AND MS.TPNOTA = 512) T1,

(SELECT SUM(VLCONT) VLIMPRESSORA
FROM   PDV_FISCAL
WHERE  CODFIL = &CODFIL
AND DATA = TO_DATE(&DATA)
AND TIPO = 'F') T2
