--entendendo retomada

-- Retomada   
SELECT SUM(VLTOTAL) "Retomada"
FROM   (SELECT I.CODFIL, I.TPNOTA, I.NUMNOTA, I.SERIE, I.DTNOTA, I.CODITPROD, I.NUMPEDVEN, CAST(I.VLTOTAL AS NUMBER(15, 2)) VLTOTAL, 
       TRUNC(SYSDATE) DTIMPORT, I.FILPED, I.ITEM, P.STATUS,  S.STATUS AS STATUSNOTA
        
       FROM   MOV_SAIDA S 
       INNER  JOIN MOV_ITSAIDA I ON S.CODFIL = I.CODFIL
			        AND S.TPNOTA = I.TPNOTA
			        AND S.NUMNOTA = I.NUMNOTA
			        AND S.SERIE = I.SERIE
			        AND S.DTNOTA = I.DTNOTA
			        AND I.NUMPEDVEN <> 999999
         INNER  JOIN MOV_PEDIDO P ON S.NUMPEDVEN = P.NUMPEDVEN
			       AND S.FILPED = P.CODFIL
                WHERE  S.TPNOTA = 512
	      AND P.CODFIL IN (&CODFIL, &CODDEP)
	      AND S.DTNOTA = '&DATA'
         GROUP  BY I.CODFIL, I.TPNOTA, I.NUMNOTA, I.SERIE, I.DTNOTA, I.CODITPROD, I.NUMPEDVEN, I.VLTOTAL, I.FILPED, I.ITEM, P.STATUS, S.STATUS)


SELECT sum(s.vltotal)
FROM   MOV_ITSAIDA S
INNER  JOIN MOV_PEDIDO P ON S.NUMPEDVEN = P.NUMPEDVEN
		      AND S.FILPED = P.CODFIL
WHERE  S.CODFIL IN (2, 502)
       AND S.DTNOTA = '11/11/2015'
       AND S.NUMPEDVEN <> 999999
       AND S.TPNOTA = 512
       and S.status =2 
