SELECT * FROM (SELECT A.CODFIL, A.NUMCXA, SUM(A.VLTOTAL) VLSAIDA, A.NUMNOTA, B.NUMNOT, SUM(B.VALLAN) AS VLLANCTO

FROM MOV_SAIDA A  LEFT JOIN CXA_LANCTO B
ON A.CODFIL = B.CODFIL 
AND A.NUMCXA = B.NUMCXA
AND A.NUMNOTA = B.NUMNOT
AND A.DTNOTA = B.DATENT


WHERE A.CODFIL = &CODFIL
AND DTNOTA = TO_DATE('11/01/2015')
AND A.TPNOTA = 512

GROUP BY A.CODFIL, A.NUMCXA, A.NUMNOTA, B.NUMNOT

HAVING A.NUMCXA IS NOT NULL)
WHERE VLSAIDA <> VLLANCTO
