SELECT CXA_LANCTO.FORMA FORMA, MAX(CXA_LANCTO.CONDPGTO) CONDPG, CXA_EVENTO.DSCEVE, SUM(CXA_LANCTO.VALLAN) SOMA_LANCTO, MAX(CXA_MOVIMENTO.OBS), MAX(CXA_EVENTO.FLDIN) DINHEIRO, COUNT(CXA_LANCTO.FORMA)
FROM   CXA_EVENTO, CXA_LANCTO, CXA_MOVIMENTO, CAD_FORMA
WHERE  CXA_LANCTO.CODFILCXA = 10
       AND CXA_LANCTO.NUMCXA = 68
       AND CXA_LANCTO.NUMMOV = 1
       AND CXA_LANCTO.CODOPER = 125
       AND CXA_LANCTO.CODFILCXA = CXA_MOVIMENTO.CODFIL
       AND CXA_LANCTO.STATUS <> 9
       AND CXA_LANCTO.CODOPER = CXA_MOVIMENTO.CODOPER
       AND CXA_LANCTO.NUMCXA = CXA_MOVIMENTO.NUMCXA
       AND CXA_LANCTO.NUMMOV = CXA_MOVIMENTO.NUMMOV
       AND CXA_LANCTO.DATENT = CXA_MOVIMENTO.DATAINI
       AND CXA_LANCTO.CODEVE <> 0
       AND CXA_EVENTO.CODEVE <> 19
       AND CAD_FORMA.FORMA = CXA_LANCTO.FORMA
       AND CAD_FORMA.CONDPGTO = CXA_LANCTO.CONDPGTO
       AND CAD_FORMA.CODFIL = CXA_LANCTO.CODFIL
       AND ((CAD_FORMA.GERCXA = 'S') OR (CAD_FORMA.FLGERAER = 'S'))
       AND CXA_EVENTO.CODEVE = CXA_LANCTO.FORMA
       AND (CXA_EVENTO.FLEMITECOBRANCA NOT IN ('B', 'C') OR CXA_EVENTO.FLEMITECOBRANCA IS NULL)
       AND CXA_LANCTO.DATENT = TO_DATE('18/02/2016', 'DD/MM/YYYY')
GROUP  BY CXA_LANCTO.FORMA, CXA_EVENTO.DSCEVE, CXA_MOVIMENTO.CODOPER, CXA_MOVIMENTO.DATAINI, CXA_MOVIMENTO.NUMCXA, CXA_MOVIMENTO.NUMMOV
ORDER  BY CXA_LANCTO.FORMA, CONDPG
