SELECT CXA_LANCTO.CODEVE, CAD_FORMA.DESCRICAO, SUM(CXA_LANCTO.VALLAN)
FROM   CXA_LANCTO
INNER JOIN CAD_FORMA   
ON 
CXA_LANCTO.CODEVE = CAD_FORMA.FORMA

WHERE  CXA_LANCTO.CODFIL = &FILIAL
       AND CXA_LANCTO.NUMCXA = &CAIXA
       AND CXA_LANCTO.DATENT = '&DATA'
       AND CXA_LANCTO.TPNOTA = 512
       AND CXA_LANCTO.STATUS =2  
       AND CXA_LANCTO.CODOPER = &OPERADOR
       GROUP BY CXA_LANCTO.CODEVE, CAD_FORMA.DESCRICAO
	  
	  
     
