SELECT CONT.FORMA, SUM(CONT.VLFORMA) CONTAGEM, MAX(EVE.DSCEVE)
FROM   CXA_CONTAGEM CONT, CXA_EVENTO EVE
WHERE  CONT.CODFIL = &CODFIL
       AND CONT.NUMCXA = &CAIXA
       AND CONT.DATAINI = TO_DATE('&DATA', 'DD/MM/YYYY')
       AND CONT.NUMOV = 1
       AND CONT.CODOPER = &CODOPER
       AND CONT.FORMA = EVE.CODEVE
GROUP  BY CONT.FORMA
