SELECT VALOR_GEMCO, VALOR_IMPRESSORA, (VALOR_GEMCO - VALOR_IMPRESSORA) DIFERENCA FROM 
(SELECT SUM(VLTOTAL) VALOR_GEMCO
FROM MOV_SAIDA
WHERE CODFIL = &FILIAL
AND NUMCXA = &CAIXA
AND DTNOTA = '&DATA'
AND TPNOTA = 512
AND STATUS <> 9) GEMCO
                                                  ,                                                            
(SELECT VLCONT VALOR_IMPRESSORA -- ESTE CAMPO CONTÉM AS INFORMAÇÕES DO VALOR TOTAL - VALOR CANCELADO
FROM   PDV_FISCAL
WHERE  CODFIL = &FILIAL
       AND PDV = &CAIXA
       AND DATA = '&DATA'
       AND TIPO = 'F') 
       IMPRESSORA           
