-- Verifica divergencia status Nota x Lancto
SELECT MS.CODFIL,
       MS.NUMNOTA,
       MS.SERIE,
       MS.NUMPEDVEN,
       MS.DTNOTA,
       SUM(CL.VALLAN) AS VLLANCTO,
       MS.VLTOTAL,
       MS.STATUS AS "STATUS CF",
       CL.STATUS AS "STATUS LANCTO"
     FROM MOV_SAIDA MS
 INNER JOIN CXA_LANCTO CL ON MS.CODFIL = CL.CODFIL
                         AND MS.DTNOTA = CL.DATENT
                         AND MS.SERIE = CL.SERIE
                         AND MS.NUMNOTA = CL.NUMNOT
 WHERE MS.CODFIL = &CODFIL
   AND MS.DTATUEST >= TO_DATE ('&DATA1 00:00:00','DD/MM/YYYY HH24:MI:SS')
   AND MS.DTATUEST <= TO_DATE ('&DATA2 23:59:59','DD/MM/YYYY HH24:MI:SS')
   AND MS.DTNOTA = TO_DATE ('&DATA1','DD/MM/YYYY')
   AND MS.STATUS = 9
   AND MS.TPNOTA = 512
   AND CL.NRMULTRECEB IS NULL
   AND CL.STATUS = 2
 GROUP BY MS.CODFIL, MS.NUMNOTA, MS.SERIE, MS.NUMPEDVEN, MS.DTNOTA, MS.VLTOTAL, MS.STATUS, CL.STATUS
 ORDER BY NUMNOTA;


-- Verifica cupom sem lancto
SELECT MS.CODFIL,
       MS.NUMNOTA,
       MS.SERIE,
       MS.NUMPEDVEN,
       MS.DTNOTA,
       MS.VLTOTAL,
       MS.STATUS AS "STATUS CF",
       CL.STATUS AS "STATUS LANCTO",
       SUM(CL.VALLAN) AS VLLANCTO
     FROM MOV_SAIDA MS
 RIGHT JOIN CXA_LANCTO CL ON MS.CODFIL = CL.CODFIL
                         AND MS.DTNOTA = CL.DATENT
                         AND MS.SERIE = CL.SERIE
                         AND MS.NUMNOTA = CL.NUMNOT
 WHERE MS.CODFIL = &CODFIL
   AND MS.DTATUEST >= TO_DATE ('&DATA1 00:00:00','DD/MM/YYYY HH24:MI:SS')
   AND MS.DTATUEST <= TO_DATE ('&DATA2 23:59:59','DD/MM/YYYY HH24:MI:SS')
   AND MS.DTNOTA = TO_DATE ('&DATA1','DD/MM/YYYY')
   AND MS.STATUS <> 9
   AND MS.TPNOTA = 512
   AND CL.STATUS IS NULL
   AND MS.NUMPEDVEN > 0
   AND MS.NUMPEDVEN < 1000000
 GROUP BY MS.CODFIL, MS.NUMNOTA, MS.SERIE, MS.NUMPEDVEN, MS.DTNOTA, MS.VLTOTAL, MS.STATUS, CL.STATUS
 ORDER BY NUMNOTA;


SELECT MAX(DTATUEST)
  FROM MOV_SAIDA
 WHERE CODFIL = &CODFIL
   AND TPNOTA = 512
   AND DTNOTA = TO_DATE('&DATA1', 'DD/MM/YYYY')
