-- COLUNA: DINHEIRO
   SELECT
        Sum(CXA_LANCTO.VALLAN)
   FROM DBAGEMCO_P.CAD_FORMA CAD_FORMA,
        DBAGEMCO_P.CXA_EVENTO CXA_EVENTO,
        CXA_LANCTO CXA_LANCTO,
        DBAGEMCO_P.CXA_MOVIMENTO CXA_MOVIMENTO
   WHERE (CAD_FORMA.FLGERAER='S')
   AND   (CXA_LANCTO.STATUS<>9)
   AND   (CXA_LANCTO.CODOPER=CXA_MOVIMENTO.CODOPER)
   AND   (CXA_LANCTO.NUMCXA=CXA_MOVIMENTO.NUMCXA)
   AND   (CXA_LANCTO.NUMMOV=CXA_MOVIMENTO.NUMMOV)
   AND   (CXA_LANCTO.DATENT=CXA_MOVIMENTO.DATAINI
  And   CXA_LANCTO.DATENT=&data)
   AND   (CXA_LANCTO.CODEVE<>26)
   AND   (CXA_EVENTO.CODEVE<>19
   And   CXA_EVENTO.CODEVE=CXA_LANCTO.FORMA)
   AND   (CAD_FORMA.FORMA=CXA_LANCTO.FORMA)
   AND   (CAD_FORMA.CONDPGTO=CXA_LANCTO.CONDPGTO)
   AND   (CAD_FORMA.CODFIL=CXA_LANCTO.CODFIL)
   AND   (CXA_EVENTO.FLDIN='S')
   AND   (CXA_LANCTO.CODFILCXA=CXA_MOVIMENTO.CODFIL And
         CXA_LANCTO.CODFILCXA In (&codfil,&coddepos)) AND (CXA_EVENTO.FLEMITECOBRANCA Is Null)
         OR (CXA_LANCTO.STATUS<>9) AND (CXA_LANCTO.CODOPER=CXA_MOVIMENTO.CODOPER)
   AND   (CXA_LANCTO.NUMCXA=CXA_MOVIMENTO.NUMCXA) AND (CXA_LANCTO.NUMMOV=CXA_MOVIMENTO.NUMMOV)
   AND   (CXA_LANCTO.DATENT=CXA_MOVIMENTO.DATAINI And CXA_LANCTO.DATENT=&data) AND
         (CXA_LANCTO.CODEVE<>26) AND (CXA_EVENTO.CODEVE<>19 And CXA_EVENTO.CODEVE=CXA_LANCTO.FORMA)
   AND   (CAD_FORMA.FORMA=CXA_LANCTO.FORMA) AND (CAD_FORMA.CONDPGTO=CXA_LANCTO.CONDPGTO) AND
         (CAD_FORMA.CODFIL=CXA_LANCTO.CODFIL) AND (CXA_EVENTO.FLDIN='S') AND
         (CXA_LANCTO.CODFILCXA=CXA_MOVIMENTO.CODFIL And CXA_LANCTO.CODFILCXA In (&codfil,&coddepos)) AND
         (CXA_EVENTO.FLEMITECOBRANCA Is Null) AND (CAD_FORMA.GERCXA='S')
