-- 6.1 - Vales emitidos por devolução
SELECT SUM(VLORIG)"6.1"
  FROM CRC_TITULO
 WHERE TPCLICRC = 1
   AND CODFIL IN (&CODFIL, &CODDEP)
   AND DTEMISSAO = '&DATA'
   AND DESDTIT <> '01'
   AND NUMNOTA IS NOT NULL;

-- 10 - DEVOLUÇÃO DE VENDA
SELECT SUM(EN.VLTOTAL)"10"
  FROM ENT_NOTA EN, MOV_SAIDA MV
 WHERE EN.CODFILSAI = MV.CODFIL
   AND EN.NUMNOTASAI = MV.NUMNOTA
   AND EN.TPNOTASAI = MV.TPNOTA
   AND EN.SERIESAI = MV.SERIE
   AND EN.DTNOTASAI = MV.DTNOTA
   AND EN.CODFIL IN (&CODFIL, &CODDEP)
   AND EN.TPNOTA IN (5, 53)
   AND EN.DTNOTA = '&DATA'
   AND EN.STATUS <> 9
   AND MV.CONDPGTO <> 33;

-- Vales emitidos por canc. pedido
SELECT SUM(VLORIG) "6.2"
  FROM CRC_TITULO
 WHERE TPCLICRC = 1
   AND CODFIL IN (&CODFIL, &CODDEP)
   AND DTEMISSAO = '&DATA'
   AND DESDTIT <> '01'
   AND NUMNOTA IS NULL
   AND TIPOPED IS NOT NULL;

-- Vales emitidos no contas receber
SELECT SUM(VLORIG) "6.3"
  FROM CRC_TITULO
 WHERE TPCLICRC = 1
   AND CODFIL IN (&CODFIL, &CODDEP)
   AND DTEMISSAO = '&DATA'
   AND CODORIGCRC = 17;

-- Vales baixados no caixa
SELECT SUM(VALLAN) "6.5"
  FROM CXA_LANCTO
 WHERE CODFIL = &CODFIL
   AND DATENT = '&DATA'
   AND STATUS = 2
   AND CODEVE = 17;

-- Vales baixados por reembolso de troca
SELECT SUM(VALOR) "6.6"
  FROM CXA_SANGRIA
 WHERE CODFIL = &CODFIL
   AND DATDEP = '&DATA'
   AND CODEVE = 35;



