PRINT ' '
PRINT ' '
PRINT ' '
PRINT ' -- **************************************'
PRINT ' -- **            SMTI150009.sql ' 
PRINT ' -- **************************************'


 -- Atualiza tabela de controle de scripts executados
insert into gemco_scripts_executados (script, dthrexecucao) select 'SMTI150009.sql', getdate()
go


if exists (select '' from SYSOBJECTS where NAME = 'FILIAL_COMPL')
 drop view dbo.FILIAL_COMPL
go

create VIEW DBO.FILIAL_COMPL AS
SELECT CFIL.CODFIL,
       CFIL.PDESCTOTALPDV,
       CFIL.VLMINDESCTOTALPDV,
       CFIL.FLDESCAUTOITEM,
       CFIL.ALIQICMSFRETE,
       CFIL.FLMULTIREC,
       CFIL.FLCONFITEMPED,
       CFIL.FLALTCONDPGPED,
       CFIL.FLEMITEISSSEPARADO,
       CFIL.FLORCAMENTO,
       CFIL.FLCARTAODESC,
       CFIL.FLREDUDIFER,
       CFIL.FLPRODPESPDV,
       CFIL.FLAUTENTICESTACIONAMENTO,
       CFIL.VLMINAUTENTICESTACIONAMENTO,
       CFIL.FLCONSISTEDESC,
       CFIL.TPVERIFICAAVALLIMCRED,
       CFIL.FLCONSCODBARRAMDB,
       CFIL.FLPEDIDOCARTAOECF,
       CFIL.FLPDVRECTITBANCO,
       CFIL.FLCAMPPROMOCAO,
       CFIL.VLMINPROM,
       CFIL.FLIMPRELGERPEDRET,
       CFIL.MENSAGEMPRODVENDA,
       CFIL.FLSOLICITACPFCNPJPDV,
       CFIL.CONDPGTORECCEL,
       CFIL.TPDESCMDB,
       CFIL.MSGICMSCUPOM,
       CFIL.FLIMPICMSCUPOM,
       CFIL.FLLIMITEVENDACF,
       CFIL.VLLIMITEVENDACF,
       CFIL.TOTNFPDVPEDIDO,
       CFIL.TOTNFPDVTITULO,
       CFIL.CICLOSFININVEST,
       CFIL.FLVERIFICADOCTEF,
       CFIL.FLUTILVENPRIVATE,
       CFIL.FLIMPORGAO,
       CFIL.PROCON,
       CFIL.CODECON,
       CFIL.VLMINPROMOCAO,
       CFIL.CHAVEPROMOCAO,
       CFIL.MSGPROMONESTLE,
       CFIL.FLCPFCNPJCUPOM,
       CFIL.CODFORMACANCPREVENDA,
       CFIL.CONDPGCANCPREVENDA,
       CFIL.FLSATFISCAL,
       CFIL.FLOPTACPFCPNJ,
       CFIL.FLCUPOMTROCAPDV,
       CFIL.FLCONDPGINIVENDA,
       CFIL.FUNCAOPGTOPRIVATE,
       CFIL.FLMOTORDEPROMOCOES,
       CFIL.URLMOTORDEPROMOCOES,
       '' AS FLIPISAI,
       CFIL.DTESTOQUEPAFECF,
       CFIL.HRESTOQUEPAFECF,
       CFIL.NRSERIEESTOQUEPAFECF,
       CFIL.VLLIMITECPFCNPJPDV,
       CFIL.FLLIBCREDONLINE, 
       CFIL.TIMEOUTCRED,
       CFIL.FLINSCCADFISCALDF,
       CFIL.REGESPTRIBUTISS,
       CFIL.CODSITOPE,
       CFIL.FLIMPTOTIMPOSTOSITEM,
       CFIL.FLEXIGECPFCNPJCLIENTE,
       CFIL.TPNFMANUALPDV,
       CFIL.FLATACAREJO,
       CFIL.FLIPIPRODIMP,
       CFIL.IDTOKENNFCE,
       CFIL.TOKENNFCE, 
       CFIL.FLCONFIMPCUPOMELE, 
       CFIL.FLPROIBEVENDPDV, 
       CFIL.FLIMP2VIANFCEOFF, 
       CFIL.FLAMBIENTEHOMOLOGACE,
       CFIL.FLFISCALMANAGER,
       CFIL.CODMSGTROCAPDV,
       CFIL.URLMOTORDEPROMOCOESBDLOCAL,
       CFIL.TPDEPOS, 
       CFIL.TPCOMPNFCECLICONTRIB, 
       CFIL.FLIMPRELITENSCANCPDV, 
       CFIL.CONDPGTOB2CEXPRESS, 
       CFIL.CHAVEB2CEXPRESS
  FROM CAD_FILIAL_COMPL CFIL, USUARIOBD_CODFIL UC
 WHERE CFIL.CODFIL = UC.CODFIL
   AND UC.USUARIO = SYSTEM_USER
GO



