-- Pedidos cancelados, que contenham ent_nota mas não foram gerados vales
--OPÇÃO 1 NÃO USAR
SELECT DISTINCT EN.NUMNOTA FROM ENT_NOTA EN, CRC_TITULO CRC
WHERE 1=1
AND			EN.CODFIL IN (&Filial, &Deposito)
AND 		EN.DTNOTA = To_date(&data)
AND 		EN.TPNOTA IN (5, 53)
AND 		CRC.CODFILDEV = EN.CODFIL
AND			EN.NUMNOTA NOT IN (
																									SELECT CRC.NUMNOTADEV FROM CRC_TITULO CRC 
																									WHERE EN.CODFIL = CRC.CODFILDEV 
																									AND EN.NUMNOTA = CRC.NUMNOTADEV)

--Retorna os que não tiverem recibo de devolução
SELECT * FROM (
SELECT EN.CODFIL CODFILIAL
      ,EN.NUMNOTA NOTAENTRADA
						,EN.VLTOTAL VALORTOTAL
      ,CRC.CODFILDEV CODFILIALDEVOLUCAO
      ,CRC.NUMNOTADEV NUMNOTADEVOLUCAO
						,CRC.VLORIG VALORVALE
FROM   ENT_NOTA         EN
LEFT   JOIN CRC_TITULO  CRC
ON     CRC.CODFILDEV  = EN.CODFIL
AND    CRC.NUMNOTADEV = EN.NUMNOTA
WHERE  EN.CODFIL      = &Filial
AND    EN.DTNOTA      = TO_DATE(&data)
AND 			EN.TPNOTA 							IN (5, 53)) Tabela
WHERE  NUMNOTADEVOLUCAO IS NULL



--NAO ESTA FUNCIONANDO

SELECT DISTINCT EN.CODFIL CODFIL
      ,EN.NUMNOTA ENT_NOTA
						,EN.VLTOTAL VALORTOTAL
      ,CRC.CODFILDEV CODFILDEVOLUC
      ,CRC.NUMNOTADEV NUMNOTADEVOLUC
						,CRC.VLORIG VLORIG
FROM   ENT_NOTA         EN
LEFT   JOIN CRC_TITULO  CRC
ON     CRC.CODFILDEV  = EN.CODFIL
AND    CRC.NUMNOTADEV = EN.NUMNOTA
WHERE  EN.CODFIL      = &Filial
AND    EN.DTNOTA      = TO_DATE(&data)
AND 			EN.TPNOTA 							IN (5, 53)
GROUP BY EN.CODFIL, EN.NUMNOTA, EN.VLTOTAL, CRC.CODFILDEV, CRC.NUMNOTADEV, CRC.VLORIG


--simples retorna todos
SELECT EN.CODFIL CODFILIAL
      ,EN.NUMNOTA NOTAENTRADA
						,EN.VLTOTAL VALORTOTAL
      ,CRC.CODFILDEV CODFILIALDEVOLUCAO
      ,CRC.NUMNOTADEV NUMNOTADEVOLUCAO
						,CRC.VLORIG VALORVALE
FROM   ENT_NOTA         EN
LEFT   JOIN CRC_TITULO  CRC
ON     CRC.CODFILDEV  = EN.CODFIL
AND    CRC.NUMNOTADEV = EN.NUMNOTA
WHERE  EN.CODFIL      = &Filial
AND    EN.DTNOTA      = TO_DATE(&data)
AND 			EN.TPNOTA 							IN (5, 53)