SELECT TIT.CODFIL, TIT.NUMTIT, TIT.NUMRECDEVOL, TIT.DTENTREGA, TIT.DTEMISSAO, TIT.VLORIG, TIT.SLDTIT, TIT.NUMPED, MP.VLTOTAL
  FROM CRC_TITULO TIT
 INNER JOIN CRC_ORIGEM ORIG ON TIT.CODORIGCRC = ORIG.CODORIGCRC
 AND ORIG.CODGRPORIGCRC = 8
 INNER JOIN MOV_PEDIDO MP 
 ON MP.CODFIL = TIT.CODFIL
 AND MP.NUMPEDVEN = TIT.NUMPED                           
 WHERE TPCLICRC = 1
   AND TIT.CODFIL IN (&CODFIL, &CODDEP)
   AND TIT.DTEMISSAO = '&DATA'
   AND TIT.STATUS <> 9
   AND TIT.NUMNOTA IS NULL
   AND TIT.TIPOPED IS NOT NULL
   ORDER BY TIT.NUMTIT