SELECT MS.CODFIL    FILIAL
      ,MS.DTNOTA    DATA
      ,MS.NUMNOTA   NOTA
      ,MI.NUMPEDVEN PEDIDO_ITEM
      ,MS.NUMPEDVEN PEDIDO_CAPA
      ,MI.VLTOTITEM VALOR
      ,MI.CODITPROD
      ,MS.IDENTPROC
  FROM MOV_SAIDA MS
 INNER JOIN MOV_ITSAIDA MI ON MI.CODFIL = MS.CODFIL
                          AND MI.TPNOTA = MS.TPNOTA
                          AND MI.NUMNOTA = MS.NUMNOTA
                          AND MI.SERIE = MS.SERIE
                          AND MI.DTNOTA = MS.DTNOTA
 WHERE MS.CODFIL = &CODFIL
   AND MS.DTNOTA = '&DATA'
   AND MS.TPNOTA = 512
   AND MS.STATUS <> 9
   AND MI.NUMPEDVEN <> MS.NUMPEDVEN
   AND MI.NUMPEDVEN <> 999999