-- Vendas Retomada
SELECT  CODFIL    FILIAL
       ,NUMNOTA   NOTA
       ,SERIE     SERIE
       ,DTNOTA    "Data da Nota"
       ,NUMPEDVEN PEDIDO
       ,FILPED    "Filial Ped."
       ,VLTOTAL   VALOR
  FROM MOV_SAIDA
 WHERE CODFIL = &CODFIL       
   AND TPNOTA = 512
   AND DTNOTA = '&DATA'
   AND STATUS <> 9
 ORDER BY NUMNOTA

-- Verifica vendas auto-serviço
SELECT MI.CODFIL FILIAL, MI.DTNOTA DATA, MI.NUMNOTA NOTA, MI.NUMPEDVEN PEDIDO, SUM (MI.VLTOTITEM) VALOR
FROM MOV_ITSAIDA MI
WHERE MI.CODFIL = &CODFIL
AND MI.TPNOTA = 512
and MI.DTATUEST >= to_date('&DATA 00:00:00','DD/MM/YYYY HH24:MI:SS')
and MI.DTATUEST <= to_date('&DATA1 23:59:59','DD/MM/YYYY HH24:MI:SS')
and MI.DTNOTA = '&DATA'
AND MI.STATUS <> 9
AND MI.NUMPEDVEN < 1000000 
AND MI.NUMPEDVEN > 0 
AND MI.NUMPEDVEN IS NOT NULL
GROUP BY MI.CODFIL, MI.DTNOTA, MI.NUMNOTA, MI.NUMPEDVEN
ORDER BY MI.NUMNOTA;

-- Verifica lançamentos de caixa para auto-serviço
SELECT CODFIL, DATENT, NUMNOT, NUMPED, SUM(VALLAN)
  FROM CXA_LANCTO
 WHERE CODFIL = &CODFIL
   AND DATENT = '&DATA'
   AND STATUS = 2
   AND NUMPED < 1000000 
   AND NUMPED > 0 
   AND NUMPED IS NOT NULL
 GROUP BY CODFIL, DATENT, NUMNOT, NUMPED
 ORDER BY NUMNOT
 
-- Verifica lançamentos de caixa para auto-serviço
SELECT CODFIL, DATENT, CODEVE, SUM(VALLAN)
  FROM CXA_LANCTO
 WHERE CODFIL = &CODFIL
   AND DATENT = '&DATA'
   AND STATUS = 2
   AND CODEVE IN (1,2,6,7,17,29,30)
 GROUP BY CODFIL, DATENT, CODEVE






-- Verifica lançamentos de caixa para pedidos
SELECT CODEVE, SUM(VALLAN) FROM CXA_LANCTO
WHERE CODFIL = &CODFIL
AND DATENT = '&DATA'
AND STATUS = 2
AND NUMPED <> 999999 
AND NUMPED <> 0 
GROUP BY CODEVE  

-- Verificada Vendas por pedido

SELECT MI.CODFIL FILIAL, MI.DTNOTA DATA, MI.NUMNOTA NOTA, MI.NUMPEDVEN PEDIDO, SUM (MI.VLTOTITEM) VALOR
FROM MOV_ITSAIDA MI
WHERE MI.CODFIL = 02
AND MI.TPNOTA = 512
AND MI.DTNOTA = '29/05/2015'
AND MI.DTATUEST >= '02/05/2015'
AND MI.DTATUEST <  '02/05/2015'
AND MI.STATUS <> 9
AND MI.NUMPEDVEN <> 999999
/*AND MI.NUMPEDVEN < 1000000
AND MI.NUMPEDVEN > 0*/
GROUP BY MI.CODFIL, MI.DTNOTA, MI.NUMNOTA, MI.NUMPEDVEN
ORDER BY MI.NUMNOTA;

--Retomada

SELECT MS.CODFIL FILIAL, MS.DTNOTA DATA, MS.NUMNOTA NOTA, MI.NUMPEDVEN PEDIDO_ITEM, MS.NUMPEDVEN PEDIDO_CAPA, MI.VLTOTAL VALOR, MI.CODITPROD 
FROM MOV_SAIDA MS
INNER JOIN MOV_ITSAIDA MI ON MI.CODFIL = MS.CODFIL
                         AND MI.TPNOTA = MS.TPNOTA
                         AND MI.NUMNOTA = MS.NUMNOTA
                         AND MI.SERIE = MS.SERIE
                         AND MI.DTNOTA = MS.DTNOTA
WHERE MS.CODFIL = &CODFIL
AND MS.DTNOTA = '&DATA'
AND MS.TPNOTA = 512
AND MS.STATUS <> 9
AND MI.NUMPEDVEN <> MS.NUMPEDVEN
AND MI.NUMPEDVEN <> 999999

