SELECT /*+ PARALLEL (A 10)
           PARALLEL (B 10)*/
       A.CODFIL
      ,A.NUMCXA
      ,B.ENDERECOIP
      ,A.DTNOTA DTNOTA
      ,SUM(A.VLTOTAL) VLRMS
      ,B.VLCONT VLRPDV
      ,(SUM(A.VLTOTAL) - NVL(B.VLCONT, 0)) DIV
  FROM MOV_SAIDA A, PDV_FISCAL B
 WHERE A.CODFIL = B.CODFIL(+)
   AND A.NUMCXA = B.PDV(+)
   AND A.DTNOTA = B.DATA(+)
   AND B.TIPO(+) = 'F'
   AND A.TPNOTA = 512
   AND A.STATUS <> 9
   AND A.CODFIL NOT IN (6, 14, 519)
   AND A.CODFIL IN (&CODFIL, &CODDEP)
   AND A.SERIE NOT IN ('1', '2', '3', '4', '5')
   AND A.DTNOTA BETWEEN '&DATA1' AND '&DATA2'
 GROUP BY A.CODFIL, A.DTNOTA, A.NUMCXA, B.ENDERECOIP, B.VLCONT
HAVING ABS(SUM(A.VLTOTAL) - NVL(B.VLCONT, 0)) > 1
UNION
--NÃO EXISTE NA MOV_SAIDA
SELECT /*+ PARALLEL (B 10)*/
       B.CODFIL
      ,B.PDV        NUMCXA
      ,B.ENDERECOIP
      ,B.DATA       DTNOTA
      ,0            VLRMS
      ,B.VLCONT     VLRPDV
      ,B.VLCONT     DIV
  FROM PDV_FISCAL B
 WHERE B.DATA BETWEEN '&DATA1' AND '&DATA2'
   AND B.TIPO = 'F'
   AND B.VLCONT <> 0
   AND NOT EXISTS (SELECT 'x'
          FROM MOV_SAIDA A
         WHERE A.CODFIL = B.CODFIL
           AND A.NUMCXA = B.PDV
           AND A.DTNOTA = B.DATA
           AND A.TPNOTA = 512
           AND A.STATUS <> 9
           AND A.CODFIL NOT IN (6, 14, 519)
           AND A.DTNOTA BETWEEN B.DATA AND B.DATA)
