SELECT CL.CODFIL
      ,CL.DATENT
      ,CL.NUMPED
      ,CL.NUMCXA
      ,CL.CODOPER
      ,MP.VLTOTAL VLPED
      ,SUM(CL.VALLAN) VLLANC
      ,MP.VLTOTAL - SUM(CL.VALLAN) DIV
  FROM CXA_LANCTO CL
 INNER JOIN MOV_PEDIDO MP
    ON CL.NUMPED = MP.NUMPEDVEN
   AND MP.DTPEDIDO = CL.DATENT
 WHERE CL.CODFIL = &CODFIL
   AND CL.DATENT = '&DATA' --between '01/11/2013' and '25/11/2013'
   AND CL.NUMPED <> 999999
   --AND CL.NUMCXA = 6
   AND CL.STATUS = 2
 GROUP BY CL.CODFIL, CL.DATENT, CL.NUMPED, CL.NUMCXA, CL.CODOPER, MP.VLTOTAL
HAVING(MP.VLTOTAL - SUM(CL.VALLAN)) >= 0.5 OR (MP.VLTOTAL - SUM(CL.VALLAN)) <= -0.5
