--------------------------------------------------------------------------------
-- tbTabsCarga.sql
-- Data   : 14/08/2013
-- Autor  : Amauri
-- Criar as tabelas de carga inicial
--------------------------------------------------------------------------------

USE ArquivosAvon
GO

-- Carga inicial de arquivos TXT
Create Table CargaInicial (
  CargaInicial_ID  Int Identity(1,1) Primary Key,
  Dados            Varchar(4000) 
);

-- Carga inicial de arquivos CS28  
-- Drop Table CargaInicialCS28
Create Table CargaInicialCS28 (  
  CargaInicialCS28_ID  Int Identity(1,1) Primary Key,
  AVISO_DEBITO         Varchar(7), 
  NOME                 Varchar(50), 
  SETOR                Varchar(3), 
  REGASC               Varchar(8), 
  DT_NASCIMENTO        Varchar(10), 
  RG_RA                Varchar(13), 
  CPF_RA               Varchar(14), 
  DDD_TEL              Varchar(17), 
  ENDERECO             Varchar(60), 
  NUMERO               Varchar(5), 
  COMP                 Varchar(20), 
  BAIRRO               Varchar(30), 
  CEP                  Varchar(8), 
  CIDADE               Varchar(20), 
  UF                   Varchar(2), 
  DT_ESTABELECIMENTO   Varchar(10), 
  EQUIPE               Varchar(3), 
  LOS                  Varchar(3), 
  AGENCIA              Varchar(33), 
  NF                   Varchar(7), 
  DT_NF                Varchar(8), 
  CAMPANHA             Varchar(2),
  CAMPANHA_ANO         Varchar(4), 
  DT_ENVIO_RA_COB      Varchar(8), 
  DT_DEVOLUCAO         Varchar(8), 
  N_AGENCIA            Varchar(3), 
  NOME_RA_INDICA       Varchar(50), 
  END_RA_INDICA        Varchar(60), 
  NUEMERO_RA_INDICA    Varchar(5), 
  COMP_RA_INDICA       Varchar(20), 
  BAIRRO_RA_INDICA     Varchar(30), 
  CEP_RA_INDICA        Varchar(8), 
  CIDADE_RA_INDICA     Varchar(20), 
  UF_RA_INDICA         Varchar(2), 
  REGASC_RA_INDICA     Varchar(8), 
  VALOR_DEBITO         Varchar(11) 
); 

-- Auxiliar para convresão de dados de arquivos CS28  
-- Drop Table ConversaoCS28
Create Table ConversaoCS28 (  
  ConversaoCS28_ID     Int Identity(1,1) Primary Key,
  AVISO_DEBITO         Int, 
  NOME                 Varchar(50), 
  SETOR                SmallInt, 
  REGASC               Int, 
  DT_NASCIMENTO        SmallDateTime, 
  RG_RA                Varchar(13), 
  CPF_RA               Varchar(14), 
  DDD_TEL              Varchar(17), 
  ENDERECO             Varchar(60), 
  NUMERO               Varchar(5), 
  COMP                 Varchar(20), 
  BAIRRO               Varchar(30), 
  CEP                  Varchar(8), 
  CIDADE               Varchar(20), 
  UF                   Varchar(2), 
  DT_ESTABELECIMENTO   SmallDateTime, 
  EQUIPE               SmallInt, 
  LOS                  SmallInt, 
  AGENCIA              Varchar(33), 
  NF                   Int, 
  DT_NF                SmallDateTime, 
  CAMPANHA             TinyInt, 
  CAMPANHA_ANO         SmallInt,
  DT_ENVIO_RA_COB      SmallDateTime, 
  DT_DEVOLUCAO         SmallDateTime, 
  N_AGENCIA            SmallInt, 
  NOME_RA_INDICA       Varchar(50), 
  END_RA_INDICA        Varchar(60), 
  NUEMERO_RA_INDICA    Varchar(5), 
  COMP_RA_INDICA       Varchar(20), 
  BAIRRO_RA_INDICA     Varchar(30), 
  CEP_RA_INDICA        Varchar(8), 
  CIDADE_RA_INDICA     Varchar(20), 
  UF_RA_INDICA         Varchar(2), 
  REGASC_RA_INDICA     Int, 
  VALOR_DEBITO         Money 
);

-- Carga inicial de arquivos C428  
-- Drop Table CargaInicialCS48
Create Table CargaInicialCS48 (  
  CargaInicialCS48_ID  Int Identity(1,1) Primary Key,
  REGASC               Varchar(8), 
  Nome                 Varchar(50), 
  Sexo                 Varchar(1), 
  Endereco             Varchar(60), 
  Numero               Varchar(5), 
  Comp                 Varchar(20), 
  Bairro               Varchar(30), 
  Cidade               Varchar(20), 
  UF                   Varchar(2), 
  CEP                  Varchar(8), 
  DDD                  Varchar(3), 
  TEL                  Varchar(8), 
  DDD_COM              Varchar(3), 
  TEL_COM              Varchar(8), 
  RAMAL                Varchar(5), 
  DDD_REC              Varchar(3), 
  TEL_REC              Varchar(8), 
  DDD_CEL              Varchar(3), 
  TEL_CEL              Varchar(8), 
  CPF_RA               Varchar(11), 
  RG_RA                Varchar(11), 
  ORGAO_EMISSOR        Varchar(5), 
  DT_NASCIMENTO        Varchar(8), 
  DT_ESTABELECIMENTO   Varchar(8) , 
  ESTADO_CIVIL         Varchar(1), 
  NOME_DO_PAI          Varchar(50), 
  NOME_DA_MAE          Varchar(50), 
  EMAIL                Varchar(50), 
  CONJUGE              Varchar(50), 
  ORDER_ID             Varchar(8), 
  CAMPANHA             Varchar(2), 
  ANO_CAMPANHA         Varchar(4), 
  VALOR_PENDENCIA      Varchar(13), 
  DT_FATURAMENTO       Varchar(8), 
  DT_VENCIMENTO        Varchar(8), 
  DT_EXPIRACAO         Varchar(8), 
  DATA_ENVIO           Varchar(8), 
  SETOR                Varchar(4), 
  COMISSAO             Varchar(13), 
  JUROS                Varchar(13), 
  NUMERO_DI            Varchar(16) 
);  

-- Auxiliar para conversão de dados de arquivos CS48  
-- Drop Table ConversaoCS48
Create Table ConversaoCS48 (  
  ConversaoCS48_ID     Int Identity(1,1) Primary Key,
  REGASC               Int, 
  Nome                 Varchar(50), 
  Sexo                 Varchar(1), 
  Endereco             Varchar(60), 
  Numero               Varchar(5), 
  Comp                 Varchar(20), 
  Bairro               Varchar(30), 
  Cidade               Varchar(20), 
  UF                   Varchar(2), 
  CEP                  Varchar(8), 
  DDD                  Varchar(3), 
  TEL                  Varchar(8), 
  DDD_COM              Varchar(3), 
  TEL_COM              Varchar(8), 
  RAMAL                Varchar(5), 
  DDD_REC              Varchar(3), 
  TEL_REC              Varchar(8), 
  DDD_CEL              Varchar(3), 
  TEL_CEL              Varchar(8), 
  CPF_RA               Varchar(11), 
  RG_RA                Varchar(11), 
  ORGAO_EMISSOR        Varchar(5), 
  DT_NASCIMENTO        SmallDateTime, 
  DT_ESTABELECIMENTO   SmallDateTime, 
  ESTADO_CIVIL         Varchar(1), 
  NOME_DO_PAI          Varchar(50), 
  NOME_DA_MAE          Varchar(50), 
  EMAIL                Varchar(50), 
  CONJUGE              Varchar(50), 
  ORDER_ID             Int, 
  CAMPANHA             TinyInt, 
  ANO_CAMPANHA         SmallInt, 
  VALOR_PENDENCIA      Money, 
  DT_FATURAMENTO       SmallDateTime, 
  DT_VENCIMENTO        SmallDateTime, 
  DT_EXPIRACAO         SmallDateTime, 
  DATA_ENVIO           SmallDateTime, 
  SETOR                SmallInt, 
  COMISSAO             Money, 
  JUROS                Money, 
  NUMERO_DI            Varchar(16) 
);  
   
   
-- Carga inicial de arquivos CS13  
-- Drop Table CargaInicialCS13
Create Table CargaInicialCS13 (  
  CargaInicialCS13_ID  Int Identity(1,1) Primary Key,
  ModeloLayout         Char(1),          -- '1'=156 caracteres '2'=191 caracteres
  TRANSACAO            Varchar(3),
  RECIBO               Varchar(6),
  REGISTRO_ASC         Varchar(8),
  DATA_TRANSACAO       Varchar(8),
  SETOR                Varchar(4),
  VALOR                Varchar(11),
  USUARIO              Varchar(10),
  HISTORICO            Varchar(30),
  TIPO_AGENCIA         Varchar(10),
  DATA_TRANSFERENCIA   Varchar(10),
  AGENCIA              Varchar(4),
  VALOR_PRINCIPAL      Varchar(11),
  JUROS                Varchar(11),
  TIMESTAMP            Varchar(26),
  SETOR_REV_COBRANCA   Varchar(4),
  Program_ID           Varchar(8),
  Campanha             Varchar(2),
  AnoCampanha          Varchar(4),
  AvisoDebito          Varchar(6),
  DataFaturamento      Varchar(10)
);

-- Auxiliar para conversão de dados de arquivos CS13  
-- Drop Table ConversaoCS13
Create Table ConversaoCS13 (  
  ConversaoCS13_ID     Int Identity(1,1) Primary Key,
  ModeloLayout         Char(1),          -- '1'=156 caracteres '2'=191 caracteres
  TRANSACAO            SmallInt,
  RECIBO               Int,
  REGISTRO_ASC         Int,
  DATA_TRANSACAO       SmallDateTime,
  SETOR                SmallInt,
  VALOR                Money,
  USUARIO              Varchar(10),
  HISTORICO            Varchar(30),
  TIPO_AGENCIA         Varchar(10),
  DATA_TRANSFERENCIA   SmallDateTime,
  AGENCIA              SmallInt,
  VALOR_PRINCIPAL      Money,
  JUROS                Money,
  TIMESTAMP            DateTime,
  SETOR_REV_COBRANCA   SmallInt,
  Program_ID           Varchar(8),
  Campanha             TinyInt,
  AnoCampanha          SmallInt,
  AvisoDebito          Int,
  DataFaturamento      SmallDateTime
);  
   
-- Carga inicial de arquivos FS1  
-- Drop Table CargaInicialFS1
Create Table CargaInicialFS1 (  
  CargaInicialFS1_ID      Int Identity(1,1) Primary Key,
  CodigoRevendedoraAsc    Varchar( 8),
  NomeRevendedora         Varchar(50),
  Sexo                    Varchar( 1),
  EnderecoRevendedora     Varchar(60),
  Numero                  Varchar( 5),
  Complemento             Varchar(20),
  Bairro                  Varchar(30),
  Cidade                  Varchar(20),
  UF                      Varchar( 2),
  CEP                     Varchar( 8),
  DDDResidencial          Varchar( 3),
  TelefoneResidencial     Varchar( 8),
  DDDComercial            Varchar( 3),
  TelefoneComercial       Varchar( 8),
  RamalComercial          Varchar( 5),
  DDDRecados              Varchar( 3),
  TelefoneRecados         Varchar( 8),
  DDDCelular              Varchar( 3),
  TelefoneCelular         Varchar( 8),
  CPF                     Varchar(11),
  RG                      Varchar(11),
  OrgaoEmissor            Varchar( 5),
  DataNascimento          Varchar( 8),
  DataEstabelecimento     Varchar( 8),
  EstadoCivil             Varchar( 1),
  NomePai                 Varchar(50),
  NomeMae                 Varchar(50),
  Email                   Varchar(50),
  NomeConjuge             Varchar(50),
  OrderId                 Varchar( 8),
  CampanhaFaturamento     Varchar( 2),
  AnoCampanhaFaturamento  Varchar( 4),
  ValorDebito             Varchar(13),
  DataFaturamento         Varchar( 8),
  DataVencimento          Varchar( 8),
  DataExpiracaoBoleto     Varchar( 8),
  DataEnvio               Varchar( 8),
  Setor                   Varchar( 4)
);

-- Auxiliar para conversão de dados de arquivos FS1  
-- Drop Table ConversaoFS1
Create Table ConversaoFS1 (  
  ConversaoFS1_ID         Int Identity(1,1) Primary Key,
  CodigoRevendedoraAsc    Int,
  NomeRevendedora         Varchar(50),
  Sexo                    Char(1),
  EnderecoRevendedora     Varchar(60),
  Numero                  Varchar( 5),
  Complemento             Varchar(20),
  Bairro                  Varchar(30),
  Cidade                  Varchar(20),
  UF                      Char(2),
  CEP                     Varchar( 8),
  DDDResidencial          Varchar( 3),
  TelefoneResidencial     Varchar( 8),
  DDDComercial            Varchar( 3),
  TelefoneComercial       Varchar( 8),
  RamalComercial          Varchar( 5),
  DDDRecados              Varchar( 3),
  TelefoneRecados         Varchar( 8),
  DDDCelular              Varchar( 3),
  TelefoneCelular         Varchar( 8),
  CPF                     Varchar(11),
  RG                      Varchar(11),
  OrgaoEmissor            Varchar( 5),
  DataNascimento          SmallDateTime,
  DataEstabelecimento     SmallDateTime,
  EstadoCivil             Char(1),
  NomePai                 Varchar(50),
  NomeMae                 Varchar(50),
  Email                   Varchar(50),
  NomeConjuge             Varchar(50),
  OrderId                 Int,
  CampanhaFaturamento     TinyInt,
  AnoCampanhaFaturamento  SmallInt,
  ValorDebito             Money,
  DataFaturamento         SmallDateTime,
  DataVencimento          SmallDateTime,
  DataExpiracaoBoleto     SmallDateTime,
  DataEnvio               SmallDateTime,
  Setor                   SmallInt
);

-- Carga inicial de arquivos FS22  
-- Drop Table CargaInicialFS22
Create Table CargaInicialFS22 (  
  CargaInicialFS22_ID  Int Identity(1,1) Primary Key,
  IDDEVEDOR            Varchar(8),
  DEVNOME              Varchar(50),
  DEVENDERECO          Varchar(65),
  DEVCOMPL             Varchar(20),
  DEVBAIRRO            Varchar(30),
  DEVCIDADE            Varchar(20),
  DEVUF                Varchar(2),
  DEVCEP               Varchar(8),
  CODIGOBANCO          Varchar(4),
  NOMEBANCO            Varchar(30),
  LINHADIGITAVEL       Varchar(60),
  LOCALPAGAMENTO       Varchar(84),
  PARCELA              Varchar(7),
  VENCIMENTO           Varchar(8),
  CEDENTE              Varchar(84),
  AGENCIACODIGOCEDENTE Varchar(19),
  CAMPANHA             Varchar(2),
  AVISO_DEBITO         Varchar(5),
  DATADOCUMENTO        Varchar(10),
  NUMERODOCUMENTO      Varchar(10),
  ESPECIEDOCUMENTO     Varchar(2),
  ACEITE               Char(1),
  DATAPROCESSAMENTO    Varchar(10),
  NOSSONUMERO          Varchar(21),
  USOBANCO             Varchar(4),
  CARTEIRA             Varchar(3),
  MOEDA                Varchar(4),
  QUANTIDADE           Varchar(5),
  VALOR                Varchar(14),
  VALORDOCUMENTO       Varchar(14),
  CIP                  Varchar(3),
  BONIFICACAO          Varchar(12),
  COMISSAO             Varchar(12),
  INSTRUCAO01          Varchar(98),
  INSTRUCAO02          Varchar(98),
  INSTRUCAO03          Varchar(98),
  INSTRUCAO04          Varchar(98),
  INSTRUCAO05          Varchar(98),
  INSTRUCAO06          Varchar(98),
  INSTRUCAO07          Varchar(98),
  INSTRUCAO08          Varchar(98),
  INSTRUCAO09          Varchar(98),
  CODIGOBARRAS         Varchar(44)
);

-- Auxiliar para conversão de dados de arquivos FS22  
-- Drop Table ConversaoFS22
Create Table ConversaoFS22 (  
  ConversaoFS22_ID     Int Identity(1,1) Primary Key,
  IDDEVEDOR            Int,
  DEVNOME              Varchar(50),
  DEVENDERECO          Varchar(65),
  DEVCOMPL             Varchar(20),
  DEVBAIRRO            Varchar(30),
  DEVCIDADE            Varchar(20),
  DEVUF                Varchar(2),
  DEVCEP               Varchar(8),
  CODIGOBANCO          SmallInt,
  NOMEBANCO            Varchar(30),
  LINHADIGITAVEL       Varchar(60),
  LOCALPAGAMENTO       Varchar(84),
  PARCELA              Varchar(7),
  VENCIMENTO           SmallDateTime,
  CEDENTE              Varchar(84),
  AGENCIACODIGOCEDENTE Varchar(19),
  CAMPANHA             TinyInt,
  AVISO_DEBITO         Int,
  DATADOCUMENTO        SmallDateTime,
  NUMERODOCUMENTO      Varchar(10),
  ESPECIEDOCUMENTO     Varchar(2),
  ACEITE               Char(1),
  DATAPROCESSAMENTO    SmallDateTime,
  NOSSONUMERO          Varchar(21),
  USOBANCO             Varchar(4),
  CARTEIRA             Varchar(3),
  MOEDA                Varchar(4),
  QUANTIDADE           Varchar(5),
  VALOR                Money,
  VALORDOCUMENTO       Money,
  CIP                  SmallInt,
  BONIFICACAO          Money,
  COMISSAO             Money,
  INSTRUCAO01          Varchar(98),
  INSTRUCAO02          Varchar(98),
  INSTRUCAO03          Varchar(98),
  INSTRUCAO04          Varchar(98),
  INSTRUCAO05          Varchar(98),
  INSTRUCAO06          Varchar(98),
  INSTRUCAO07          Varchar(98),
  INSTRUCAO08          Varchar(98),
  INSTRUCAO09          Varchar(98),
  CODIGOBARRAS         Varchar(44)
);

-- Carga inicial de arquivos FS23  
-- Drop Table CargaInicialFS23
Create Table CargaInicialFS23 (  
  CargaInicialFS23_ID  Int Identity(1,1) Primary Key,
  IDDEVEDOR            Varchar(8),
  DEVNOME              Varchar(50),
  DEVENDERECO          Varchar(65),
  DEVCOMPL             Varchar(20),
  DEVBAIRRO            Varchar(30),
  DEVCIDADE            Varchar(20),
  DEVUF                Varchar(2),
  DEVCEP               Varchar(8),
  CODIGOBANCO          Varchar(4),
  NOMEBANCO            Varchar(30),
  LINHADIGITAVEL       Varchar(60),
  LOCALPAGAMENTO       Varchar(84),
  PARCELA              Varchar(7),
  VENCIMENTO           Varchar(8),
  CEDENTE              Varchar(84),
  AGENCIACODIGOCEDENTE Varchar(19),
  DATADOCUMENTO        Varchar(10),
  NUMERODOCUMENTO      Varchar(10),
  ESPECIEDOCUMENTO     Varchar(2),
  ACEITE               Char(1),
  DATAPROCESSAMENTO    Varchar(10),
  NOSSONUMERO          Varchar(21),
  USOBANCO             Varchar(4),
  CARTEIRA             Varchar(3),
  MOEDA                Varchar(4),
  QUANTIDADE           Varchar(5),
  VALOR                Varchar(14),
  VALORDOCUMENTO       Varchar(14),
  CIP                  Varchar(3),
  BONIFICACAO          Varchar(12),
  COMISSAO             Varchar(12),
  INSTRUCAO01          Varchar(98),
  INSTRUCAO02          Varchar(98),
  INSTRUCAO03          Varchar(98),
  INSTRUCAO04          Varchar(98),
  INSTRUCAO05          Varchar(98),
  INSTRUCAO06          Varchar(98),
  INSTRUCAO07          Varchar(98),
  INSTRUCAO08          Varchar(98),
  INSTRUCAO09          Varchar(98),
  CODIGOBARRAS         Varchar(44),
  Datadenascimento     Varchar(10),
  Sexo                 Char(1),
  CPF                  Varchar(14),
  Setor                Varchar( 5),
  DatadeFaturamento    Varchar(10),
  NroCampanha          Varchar( 2),
  AnoCampanha          Varchar( 4),
);

-- Auxiliar para conversão de dados de arquivos FS23
-- Drop Table ConversaoFS23
Create Table ConversaoFS23 (  
  ConversaoFS23_ID     Int Identity(1,1) Primary Key,
  IDDEVEDOR            Int,
  DEVNOME              Varchar(50),
  DEVENDERECO          Varchar(65),
  DEVCOMPL             Varchar(20),
  DEVBAIRRO            Varchar(30),
  DEVCIDADE            Varchar(20),
  DEVUF                Varchar(2),
  DEVCEP               Varchar(8),
  CODIGOBANCO          SmallInt,
  NOMEBANCO            Varchar(30),
  LINHADIGITAVEL       Varchar(60),
  LOCALPAGAMENTO       Varchar(84),
  PARCELA              Varchar(7),
  VENCIMENTO           SmallDateTime,
  CEDENTE              Varchar(84),
  AGENCIACODIGOCEDENTE Varchar(19),
  DATADOCUMENTO        SmallDateTime,
  NUMERODOCUMENTO      Varchar(10),
  ESPECIEDOCUMENTO     Varchar(2),
  ACEITE               Char(1),
  DATAPROCESSAMENTO    SmallDateTime,
  NOSSONUMERO          Varchar(21),
  USOBANCO             Varchar(4),
  CARTEIRA             Varchar(3),
  MOEDA                Varchar(4),
  QUANTIDADE           Varchar(5),
  VALOR                Money,
  VALORDOCUMENTO       Money,
  CIP                  SmallInt,
  BONIFICACAO          Money,
  COMISSAO             Money,
  INSTRUCAO01          Varchar(98),
  INSTRUCAO02          Varchar(98),
  INSTRUCAO03          Varchar(98),
  INSTRUCAO04          Varchar(98),
  INSTRUCAO05          Varchar(98),
  INSTRUCAO06          Varchar(98),
  INSTRUCAO07          Varchar(98),
  INSTRUCAO08          Varchar(98),
  INSTRUCAO09          Varchar(98),
  CODIGOBARRAS         Varchar(44),
  Datadenascimento     SmallDateTime,
  Sexo                 Char(1),
  CPF                  Varchar(14),
  Setor                SmallInt,
  DatadeFaturamento    SmallDateTime,
  NroCampanha          TinyInt,
  AnoCampanha          SmallInt
);

-- Carga inicial de arquivos FS3  
-- Drop Table CargaInicialFS3
Create Table CargaInicialFS3 (  
  CargaInicialFS3_ID     Int Identity(1,1) Primary Key,
  CodigoRevendedoraAsc   Varchar( 8),
  OrderId                Varchar( 8),
  CampanhaFaturamento    Varchar( 2),
  AnoCampanhaFaturamento Varchar( 4),
  ValorDebito            Varchar(11),
  ValorPagamento         Varchar(11),
  DataBaixa              Varchar( 8),
  DataEnvio              Varchar( 8),
  TipoBaixa              Varchar( 1)
);

-- Auxiliar para conversão de dados de arquivos FS3
-- Drop Table ConversaoFS3
Create Table ConversaoFS3 (  
  ConversaoFS3_ID        Int Identity(1,1) Primary Key,
  CodigoRevendedoraAsc   Int,
  OrderId                Int,
  CampanhaFaturamento    TinyInt,
  AnoCampanhaFaturamento SmallInt,
  ValorDebito            Money,
  ValorPagamento         Money,
  DataBaixa              SmallDateTime,
  DataEnvio              SmallDateTime,
  TipoBaixa              Char(1)
);

-- Carga inicial de arquivos PP28  
-- Drop Table CargaInicialPP28
Create Table CargaInicialPP28 (  
  CargaInicialPP28_ID     Int Identity(1,1) Primary Key,  
  Setor                   Varchar( 4),
  RegAsc                  Varchar( 8),
  Nome_Ra                 Varchar(50),
  Dt_Lacto                Varchar(10),
  AD                      Varchar( 6),
  Vlr_Deb                 Varchar(12),
  Ano_Cp                  Varchar( 4),
  Cp                      Varchar( 2),
  Vlr_Saldo               Varchar(12) 
);

-- Auxiliar para conversão de dados de arquivos PP28
-- Drop Table ConversaoPP28
Create Table ConversaoPP28 (  
  ConversaoPP28_ID        Int Identity(1,1) Primary Key,
  Setor                   SmallInt,
  RegAsc                  Int,
  Nome_Ra                 Varchar(50),
  Dt_Lacto                SmallDateTime,
  AD                      Int,
  Vlr_Deb                 Money,
  Ano_Cp                  SmallInt,
  Cp                      TinyInt,
  Vlr_Saldo               Money 
);
  
-- Carga inicial de arquivos PP37_Carga  
-- Drop Table CargaInicialPP37_Carga
Create Table CargaInicialPP37_Carga (  
  CargaInicialPP37_Carga_ID Int Identity(1,1) Primary Key,  
  Tipo_Pend               Varchar(2),
  Status                  Char(1),
  Classificacao           Char(1),
  Nome_Regiao             Varchar(50),
  Nome_Divisao            Varchar(50),
  Cod_Banco               Varchar(3),
  Setor                   Varchar(4),
  RegAsc                  Varchar(8),
  Nome_Ra                 Varchar(50),
  Los                     Varchar(3),
  Order_ID                Varchar(6),
  Cp_Cobr                 Varchar(2),
  Ano_Cp                  Varchar(4),
  Dt_Fat                  Varchar(8),
  Dt_Venc                 Varchar(8),
  Dt_Validade             Varchar(8),
  Vlr_Fat                 Varchar(11),
  Vlr_Deb                 Varchar(11),
  Vlr_Parcial             Varchar(11),
  Vlr_Saldo               Varchar(11),
  Vlr_Misc                Varchar(12),
  Last_Cp                 Varchar(2),
  Last_Ad                 Varchar(6),
  Next_Cp                 Varchar(2),
  Next_Ad                 Varchar(6),
  Tat                     Char(1),
  Carta_Cobr              Varchar(1),
  Dt_Marc_Remessa         Varchar(8),
  N_Doc                   Varchar(6),
  Fator_Bloqueio          Char(1),
  Spur_Id                 Char(1),
  Instant_Delivery        Char(1),
  Carrier_Code            Varchar(3),
  Cod_Tr                  Varchar(3),
  Cod_GSV                 Varchar(10),
  Nome_Transp             Varchar(60),
  Rota                    Varchar(5),
  Dt_Tran                 Varchar(8),
  Equipe                  Varchar(3),
  Boleto                  Varchar(15),
  Digito_DI               Char(1)
);

-- Auxiliar para conversão de dados de arquivos PP37_Carga
-- Drop Table ConversaoPP37_Carga
Create Table ConversaoPP37_Carga (  
  ConversaoPP37_Carga_ID Int Identity(1,1) Primary Key,
  Tipo_Pend               TinyInt,
  Status                  Char(1),
  Classificacao           Char(1),
  Nome_Regiao             Varchar(50),
  Nome_Divisao            Varchar(50),
  Cod_Banco               SmallInt,
  Setor                   SmallInt,
  RegAsc                  Int,
  Nome_Ra                 Varchar(50),
  Los                     SmallInt,
  Order_ID                Int,
  Cp_Cobr                 TinyInt,
  Ano_Cp                  SmallInt,
  Dt_Fat                  SmallDateTime,
  Dt_Venc                 SmallDateTime,
  Dt_Validade             SmallDateTime,
  Vlr_Fat                 Money,
  Vlr_Deb                 Money,
  Vlr_Parcial             Money,
  Vlr_Saldo               Money,
  Vlr_Misc                Money,
  Last_Cp                 TinyInt,
  Last_Ad                 Int,
  Next_Cp                 TinyInt,
  Next_Ad                 Int,
  Tat                     Char(1),
  Carta_Cobr              TinyInt,
  Dt_Marc_Remessa         SmallDateTime,
  N_Doc                   Int,
  Fator_Bloqueio          Char(1),
  Spur_Id                 TinyInt,
  Instant_Delivery        Char(1),
  Carrier_Code            Varchar(3),
  Cod_Tr                  SmallInt,
  Cod_GSV                 Varchar(10),
  Nome_Transp             Varchar(60),
  Rota                    Int,
  Dt_Tran                 SmallDateTime,
  Equipe                  SmallInt,
  Boleto                  Varchar(15),
  Digito_DI               Char(1)
);

-- Carga inicial de arquivos PP37_Cadastro  
-- Drop Table CargaInicialPP37_Cadastro
Create Table CargaInicialPP37_Cadastro (  
  CargaInicialPP37_Cadastro_ID Int Identity(1,1) Primary Key,
  Setor                   Varchar( 4),
  RegistroAsc             Varchar( 8),         
  Classificacao           Char(1),         
  Valor_Misc              Varchar(14),         
  Nome                    Varchar(50),         
  Endereco                Varchar(60),         
  Numero                  Varchar( 5),         
  Complemento             Varchar(20),         
  Bairro                  Varchar(30),         
  Cidade                  Varchar(20),         
  UF                      Char(2),         
  Cep                     Varchar( 8),         
  DDD                     Varchar( 3),         
  Tel_Residencia          Varchar( 8),         
  DDD1                    Varchar( 3),         
  Tel_Comercial           Varchar( 8),         
  Ramal                   Varchar( 5),         
  DDD2                    Varchar( 3),         
  Tel_Recado              Varchar( 8),         
  DDD3                    Varchar( 3),         
  Celular                 Varchar( 8),         
  Cpf                     Varchar(11),         
  Rg                      Varchar(11),         
  Orgao_Emissor           Varchar( 5),         
  Data_Nasc               Varchar( 8),         
  Data_Estab              Varchar( 8),         
  Estado_Civil            Char(1),         
  Nome_Pai                Varchar(50),         
  Nome_Mae                Varchar(50),         
  Email                   Varchar(50),         
  Nome_Conjuge            Varchar(50)         
);    

-- Auxiliar para conversão de dados de arquivos PP37_Cadastro
-- Drop Table ConversaoPP37_Cadastro
Create Table ConversaoPP37_Cadastro (  
  ConversaoPP37_Cadastro_ID Int Identity(1,1) Primary Key,
  Setor                   SmallInt,
  RegistroAsc             Int,         
  Classificacao           Char( 1),         
  Valor_Misc              Money,         
  Nome                    Varchar(50),         
  Endereco                Varchar(60),         
  Numero                  Varchar( 5),         
  Complemento             Varchar(20),         
  Bairro                  Varchar(30),         
  Cidade                  Varchar(20),         
  UF                      Char(2),         
  Cep                     Varchar( 8),         
  DDD                     Varchar( 3),         
  Tel_Residencia          Varchar( 8),         
  DDD1                    Varchar( 3),         
  Tel_Comercial           Varchar( 8),         
  Ramal                   Varchar( 5),         
  DDD2                    Varchar( 3),         
  Tel_Recado              Varchar( 8),         
  DDD3                    Varchar( 3),         
  Celular                 Varchar( 8),         
  Cpf                     Varchar(11),         
  Rg                      Varchar(11),         
  Orgao_Emissor           Varchar( 5),         
  Data_Nasc               SmallDateTime,         
  Data_Estab              SmallDateTime,         
  Estado_Civil            Char( 1),         
  Nome_Pai                Varchar(50),         
  Nome_Mae                Varchar(50),         
  Email                   Varchar(50),         
  Nome_Conjuge            Varchar(50)         
);

-- Carga inicial de arquivos BA01  
-- Drop Table CargaInicialBA01
Create Table CargaInicialBA01 (  
  CargaInicialBA01_ID  Int Identity(1,1) Primary Key,
  ModeloLayout         Char(1),          -- '1'=Sem sub-transação '2'=Com sub-transação
  DebCred              Char(1),
  Setor                Varchar(3),
  RegAsc               Varchar(8),
  CampanhaNro          Varchar(2),
  CampanhaAno          Varchar(4),
  NroDocumento         Varchar(7),
  Transacao            Varchar(3),
  SubTransacao         Varchar(3),
  Debito               Varchar(14),
  Credito              Varchar(14)
);

-- Auxiliar para conversão de dados de arquivos BA01  
-- Drop Table ConversaoBA01
Create Table ConversaoBA01 (  
  ConversaoBA01_ID     Int Identity(1,1) Primary Key,
  ModeloLayout         Char(1),          -- '1'=Sem sub-transação '2'=Com sub-transação
  DebCred              Char(1),
  Setor                SmallInt,
  RegAsc               Int,
  CampanhaNro          TinyInt,
  CampanhaAno          SmallInt,
  NroDocumento         Varchar(7),
  Transacao            SmallInt,
  SubTransacao         SmallInt,
  Debito               Money,
  Credito              Money
);

-- FIM
